from jinja2 import Template
from datetime import datetime

def generate_pdf_report(metrics: dict, filename: str, sensitive_cols: list, domain: str) -> bytes:
    """Generates a simple HTML report (convert to PDF with WeasyPrint)"""
    
    html_template = """
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; padding: 40px; color: #1a1a1a; }
            h1 { color: #c0392b; }
            h2 { color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 8px; }
            .risk-score { font-size: 48px; font-weight: bold; color: {{ risk_color }}; }
            .metric-card { background: #f8f9fa; padding: 16px; margin: 10px 0; border-radius: 8px; }
            .warning { background: #fff3cd; padding: 12px; border-left: 4px solid #ffc107; margin: 8px 0; }
            .critical { background: #f8d7da; padding: 12px; border-left: 4px solid #dc3545; margin: 8px 0; }
            table { width: 100%; border-collapse: collapse; margin: 16px 0; }
            th { background: #2c3e50; color: white; padding: 10px; text-align: left; }
            td { padding: 10px; border-bottom: 1px solid #dee2e6; }
            .footer { margin-top: 40px; font-size: 12px; color: #888; }
        </style>
    </head>
    <body>
        <h1>🔍 FairLens Bias Audit Report</h1>
        <p><strong>Dataset:</strong> {{ filename }}</p>
        <p><strong>Domain:</strong> {{ domain }}</p>
        <p><strong>Sensitive Attributes:</strong> {{ sensitive_cols }}</p>
        <p><strong>Generated:</strong> {{ date }}</p>

        <h2>Overall Bias Risk Score</h2>
        <div class="risk-score">{{ risk_score }}/100</div>
        <p><strong>Risk Level:</strong> {{ risk_level }}</p>

        <h2>AI Explanation</h2>
        <div class="metric-card">{{ explanation }}</div>

        <h2>Fairness Metrics by Group</h2>
        {% for col, data in group_metrics.items() %}
        <h3>{{ col }}</h3>
        <table>
            <tr>
                <th>Group</th>
                <th>Positive Rate</th>
                <th>True Positive Rate</th>
                <th>False Positive Rate</th>
                <th>Count</th>
            </tr>
            {% for group_name, stats in data.groups.items() %}
            <tr>
                <td>{{ group_name }}</td>
                <td>{{ stats.positive_rate }}</td>
                <td>{{ stats.true_positive_rate }}</td>
                <td>{{ stats.false_positive_rate }}</td>
                <td>{{ stats.count }}</td>
            </tr>
            {% endfor %}
        </table>
        <div class="metric-card">
            <strong>Disparate Impact:</strong> {{ data.disparate_impact }}
            (threshold: 0.8 — below this is a legal red flag)<br/>
            <strong>Demographic Parity Difference:</strong> {{ data.demographic_parity_difference }}
        </div>
        {% endfor %}

        {% if proxy_flags %}
        <h2>⚠️ Proxy Discrimination Detected</h2>
        {% for flag in proxy_flags %}
        <div class="warning">{{ flag.warning }}</div>
        {% endfor %}
        {% endif %}

        <h2>Regulatory Flags</h2>
        {% if risk_score >= 65 %}
        <div class="critical">🚨 <strong>EU AI Act:</strong> This model may require mandatory bias testing before deployment in hiring, lending, or healthcare.</div>
        <div class="critical">🚨 <strong>NYC Local Law 144:</strong> If used for hiring in NYC, a third-party audit is legally required.</div>
        {% else %}
        <div class="metric-card">✅ No immediate regulatory violations detected. Continue monitoring.</div>
        {% endif %}

        <h2>Recommended Actions</h2>
        <div class="metric-card">
            1. <strong>Reweighing:</strong> Adjust training sample weights to balance group representation.<br/>
            2. <strong>Threshold Optimization:</strong> Apply different decision thresholds per demographic group.<br/>
            3. <strong>Proxy Removal:</strong> Remove or transform features that correlate with sensitive attributes.<br/>
            4. <strong>Regular Auditing:</strong> Re-run FairLens audit after every model retrain.
        </div>

        <div class="footer">
            Generated by FairLens v1.0 | Detect. Understand. Act. | {{ date }}
        </div>
    </body>
    </html>
    """

    risk_color = "#dc3545" if metrics["bias_risk_score"] >= 65 else \
                 "#ffc107" if metrics["bias_risk_score"] >= 35 else "#28a745"

    template = Template(html_template)
    html = template.render(
        filename=filename,
        domain=domain,
        sensitive_cols=", ".join(sensitive_cols),
        date=datetime.now().strftime("%d %B %Y, %H:%M"),
        risk_score=metrics["bias_risk_score"],
        risk_level=metrics["risk_level"],
        risk_color=risk_color,
        explanation=metrics.get("explanation", "N/A"),
        group_metrics=metrics.get("group_metrics", {}),
        proxy_flags=metrics.get("proxy_flags", []),
    )

    try:
        from xhtml2pdf import pisa
        from io import BytesIO
        result = BytesIO()
        pdf = pisa.CreatePDF(BytesIO(html.encode("utf-8")), dest=result)
        if not pdf.err:
            return result.getvalue()
        else:
            return html.encode("utf-8")
    except Exception as e:
        import traceback
        traceback.print_exc()
        return html.encode("utf-8")